version: '3.8'

volumes:
  maria:

services:

  dizzerphp:
    container_name: phpdizzer
    build:
      context: ./php
    ports:
      - '9001:9000'
    environment:
      TZ: UTC
    volumes:
      - ./app:/var/www/symfo
    depends_on:
      - dizzerbase

  dizzernginx:
    container_name: nginxdizzer
    image: nginx:stable-alpine
    ports:
      - '8080:80'
      - '8443:443'
    environment:
      TZ: UTC
    volumes:
      - ./app:/var/www/symfo
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - dizzerphp
      - dizzerbase
      - dizzernode

  dizzerbase: 
    container_name: basedizzer
    image: mariadb:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: UTC
      MYSQL_ROOT_PASSWORD: admin2024
      MYSQL_DATABASE: dizzerdata
      MYSQL_USER: dizzeruser
      MYSQL_PASSWORD: dizzer2024
    ports:
      - '3307:3306'
    volumes:
      - maria:/var/lib/mysql


  dizzernode:
    container_name: nodedizzer
    build:
      context: ./node
    volumes:
      - .app:/var/www/symfo
    restart: always
    environment:
      TZ: UTC
    depends_on:
      - dizzerphp
    tty: true